version: '3.1'
  nginx:
    restart: always
    image: nginx
    ports:
      - 8093:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./vue-asgisn/dist:/var/www/html/
      - ./vue-asgisn/static/:/static/